---
title: How to get a post-doc position?
author: Saurav
date: '2021-09-20'
slug: []
categories:
  - postdoc
tags:
  - postdoc
  - job
description: ''
keywords: []
draft: yes
---
Lot of people asked me the question,
<b>How to get postdoc position ?</b>

I will mostly talk about getting a postdoc in abroad:
In India, there are national level, postdoc fellowships you can apply and look for.


### The steps:


<li> You can ask you current professor, if he knows someone, to whom he can recommend you or refer you to the professor he knows, who is working in your field, and then you can communicate with him, describing your interest, and asks about probable opportunity available at his lab </li>


<li> Second, you can search for the professor who are working in your field, from different university websites, or best way, the papers which you referred while preparing your research report, look for the corresponding author, and individually mail them, asking about available opportunity at their labs or groups </li>


<li> Third, now a days, most of the professor post available post doc position in their twitter profile, so if you have twitter profile, search with hastags like #postdoc and your field of interests, you will find all the relevant post from the professor and individually contact them and tell them about your interest along with how you found the information </li>


### Now the hardest thing, where all of us fails

<b> writing the mail or your cover letter </b>

<b> Things to do and remember </b>

<li> dont write a whole history, professors get hundreds of mails like this, you need to standout but with less word in constructive way </li>


<li> start you letter with your introduction and what made you to reach out to him </li>


<li> write about why you are interested in his research group, what made you interested, in few words and then also describe how it will help you to grow professionally. It shouldn't sound like you will come and only help him. Be true to your cover letter describe how you can help or contribute in his/her group and at the same time how it will also help you </li>


<li> then end your letter, thats it. Dont stretch it too much. Its always better to attach your CV with your cover letter and two or three of your best paper with the letter as attachment, which will describe your current field and writing efficiency. As for postdoc, communication and writing efficiency is really important. At the same time paper will aslo describe your scientific proficiency. </li>


Preety much that's it. you can mail me if you need some help. you can follow me in my [twitter](https://twitter.com/ConfusedPostdoc),I frequently shares the post doc position which are available especially in microbiology and agricultural field.

=======
