---
title: POST DOC IN QUANTITATIVE CONSERVATION ECOLOGY AND MACHINE LEARNING
author: Assam
date: '2020-10-26'
slug: post-doc-in-quantitative-conservation-ecology-and-machine-learning
categories:
  - postdoc
tags:
  - job
  - postdoc
description: ''
keywords: []
draft: no
math: no
toc: no
---
We currently have a fully-funded postdoctoral fellowship for up to three years in the area of quantitative conservation ecology and machine learning. If you or someone you know is passionate about this topic and fits the description below, read on!

The due date for applications is Nov. 15, 2020. 

---

[Post-Doctoral Research Fellowship in Quantitative Conservation Ecology and Machine Learning](https://www.oceansphere.org/news/2018/8/22/postdoctoral-fellowship-available-applying-emerging-technologies-to-understand-human-impacts-on-coral-reefs-m9hca)
HAWAIʻI INSTITUTE OF MARINE BIOLOGY, UNIVERSITY OF HAWAIʻI AT MĀNOA
FELLOWSHIP DESCRIPTION AND DUTIES:  
The Elizabeth Madin Laboratory at the University of Hawai‘i at Mānoa’s Hawai‘i
Institute of Marine Biology is seeking to recruit a postdoctoral fellow in the area of quantitative conservation ecology to join our lab. The position will be funded by a recent NSF CAREER award focused on decoding seascape-scale vegetation patterns on coral reefs to understand ecosystem health.

RESEARCH CONTEXT AND SPECIFIC FOCUS:
Human impacts on coral reefs continue to accumulate from a variety of sources, including climate change, fishing and other types of resource extraction, pollution, habitat alteration, and others. Meanwhile, recent advances in remote imaging (e.g., high-resolution satellite and drone imagery), tracking (e.g., automated vessel tracking), and other technologies allow quantification of changes to human activities and coral reef ecosystems in near-real time over local to global scales. 

The successful candidate will design and lead research investigating human impacts on coral reefs through the use of new and emerging tools capable of rapidly advancing coral reef science and conservation. Specifically, the postdoc will take a leadership role in 1) the creation of the machine learning algorithms for automated detection and measurement of reef halos from high-resolution satellite imagery, and 2) the integration of results arising from these methods with existing datasets. The postdoc will also be encouraged and supported to develop/execute their own broadly-related research questions (see “Appointment and application” below). Additionally, the postdoc will be actively engaged in mentoring of graduate students/interns and possibly teaching of graduate students.

REQUIRED QUALIFICATIONS: 
A Ph.D. in computer science, quantitative geography/spatial data analysis, mathematical biology, statistics, quantitative ecology, or oceanography;

Publication record that illustrates an ability to conduct novel, independent research; 

Considerable experience processing, manipulating, and analyzing large datasets;

Demonstrated proficiency with R (or related programming languages) and with software tools for analyzing geospatial data; 

Demonstrated aptitude for applying advanced computational tools in a research setting;

Excellent problem-solving skills;

Excellent time management skills, including the ability to meet project goals in a timely manner and follow projects through to completion, and meticulous work style, as evidenced by previous research; 

Demonstrated ability to mentor, or an interest in mentoring, junior laboratory members;

Strong interpersonal and communication skills, including the ability to work both independently and collaboratively, and to communicate research findings at professional meetings and in high-quality peer-reviewed journals. 

DESIRABLE QUALIFICATIONS: 
Experience in the development of machine learning algorithms;

Experience participating in or leading marine field expeditions, including the use of snorkelling and SCUBA diving;

Experience as a small boat operator; 

Ability to travel internationally for fieldwork and/or conferences.

RESEARCH ENVIRONMENT: 
The postdoc will be based in the lab of Dr. Elizabeth Madin at the University of Hawai‘i at Mānoa’s Hawai‘i Institute of Marine Biology (HIMB). HIMB is within the School of Ocean and Earth Science and Technology (SOEST) at the University of Hawai‘i at Mānoa. HIMB provides unparalleled research opportunities, in particular due to its unique location on Moku o Lo‘e Island (Coconut Island) surrounded by a coral reef in Kāne‘ohe Bay on the windward side of the island of O‘ahu (~ 24 km from the main university campus in Mānoa).

The Madin lab provides a supportive and stimulating research environment with a group of highly collegial scientists who are committed to scientific outreach and policy, to open science, and to enhancing diversity in STEM. We offer a family-friendly, flexible work environment where work-life balance is encouraged.

APPOINTMENT AND APPLICATION: 
The postdoc fellowship is initially for one year, renewable for up to three years based on performance and funding availability. Fellowship stipend is commensurate with experience within guidelines set by the university. The start date is flexible, but would ideally be no later than July 2021. 

To apply: Candidates should submit the following materials via email to Dr. Madin (emadin@hawaii.edu) in a single PDF document, with the file name “MadinLabPostdocApplication_YourLastName” your last name in the file name and the email subject heading “Madin Lab postdoc application” by Nov. 15, 2020 (Hawai‘i – Aleutian Standard Time):

A cover letter briefly explaining your motivation for applying for this fellowship, how your prior research experience qualifies you for the fellowship, and how you satisfy the required and desirable qualifications (in dot-point format); 

A short (1-2 page) research proposal describing the independent research you would like to undertake (proposals that are creative, scale-able, and relevant to coral reef conservation are encouraged);

A CV, including publication list (which may include publications in advanced stages of preparation that will be likely in the review process by the above postdoctoral fellowship deadline date) and names and contact details for three references; 

Quality and originality of the research proposal, individual qualifications and background, academic excellence, and collegiality will be the primary criteria in selecting the successful candidate. 

The Madin Lab is committed to equality and diversity and we encourage applications from STEM-underrepresented minorities (particularly people of Hawaiian and other Pacific Islander backgrounds), women, and persons with disabilities. International applicants are also welcome and encouraged to apply. 
