---
title: Postdoctoral position in quantitative/statistical/population genetics, bioinformatics
author: ''
date: '2020-10-19'
slug: postdoctoral-position-in-quantitative-statistical-population-genetics-bioinformatics
categories:
  - postdoc
tags:
  - postdoc
  - job
description: ''
keywords: []
draft: yes
---
**Working Title**	
Post-Doctoral Research Associate
Department	Agronomy & Horticulture-0827
University of Nebraska - Lincoln, Nebraska, USA

Requisition Number	F_190182

Posting Open Date	09/30/2019
Application Review Date: (To ensure consideration, please submit all application materials before review date)	10/31/2019

Posting Close Date	
Open Until Filled	Yes

**Description of Work**	
The Post-Doctoral Research Associate will contribute to the integrated research land-grant mission of the home unit and the IANR, as an effective scholar and citizen, including supporting student recruitment and IANR science literacy.
This position involves conducting independent research in the area of quantitative genetics, population genetics and bioinformatics. Duties of this position involve creating and analyzing large genomic datasets for the purpose of better understanding genomic diversity in the soybean germplasm collection. The work will involve conducting studies resequencing soybean accessions including NGS library preparation and analysis of the resequencing data for whole genome SNP calling and imputation. The incumbent will be responsible for managing large-scale sequencing data and mining this large data set. In addition, the incumbent will assist with the soybean genomics program management, lab research, field research, and graduate student mentoring.
As appropriate to the appointment, the incumbent will: mentor graduate students; publish in high-quality, high-impact peer-reviewed journals, and participate in scientific meetings and other appropriate professional activities; and, translate research-based information into learner-centered products. This includes: creating scholarly, innovative, and high impact learning programs and tools; identifying issues and opportunities focused on learner needs and emerging regional and national issues with international relevance; measuring the impact of your programs and communicating results to administrators, stakeholders, users, and media; and, mentoring colleagues through professional development, translational research, grants, and professional writing.
In addition to the above-described duties, the individual will be expected to accept committee assignments, reporting responsibilities, and other special ad hoc assignments as requested at the administrative unit, college/division, institute, and or university level.

**Minimum Required Qualifications**	
• PhD required genomics, quantitative/statistical/population genetics, bioinformatics or a closely related field
• Ability to manage and analyze large-scale sequencing data is essential.
• Demonstrated ability to publish original research in peer-reviewed journals
• Excellent written and verbal communication skills

**Preferred Qualifications**
• Experience of next-generation sequencing data analysis, computational systems biology and data integration
• Experience in preparing next-generation sequencing libraries.
• Solid knowledge in population genetics such as analyzing genetic diversity and population structure of populations
• Proven skills in programming (Linux/Unix environments) and algorithm design
• Ability to work well in a team environment
• Strong interest in crop improvement.


**How to Apply**	
Click “Apply to this job” and complete the information form. Attach a letter of interest, curriculum vitae, and contact information for three professional references.

As an EO/AA employer, qualified applicants are considered for employment without regard to race, color, ethnicity, national origin, sex, pregnancy, sexual orientation, gender identity, religion, disability, age, genetic information, veteran status, marital status, and/or political affiliation. See http://www.unl.edu/equity/notice-nondiscrimination.

**For questions or accommodations related to this position contact**	
Kay McClure-Kelly
kmcclure-kelly2@unl.edu

**Job Category**	
Other Academic

**Job Type**	
Full-Time
Position funded by grant or other form of temporary funding?	Yes
	